#!/usr/bin/env bash
# Install nginx listening on port 80.

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
echo "Hello world!" | sudo tee /var/www/html/index.html
service nginx restart
