#!/usr/bin/env bash
# Configure Nginx

sudo apt-get update
sudo apt-get -y install nginx
sudo sed -i "/http {/a\         add_header X-Served-By $HOSTNAME;" /etc/nginx/nginx.conf
sudo service nginx restart
