#!/usr/bin/env bash
# script Creates the file /var/run/myscript.pid containing its PID
# displays To infinity and beyond indefinitely
# displays I hate the kill command when receiving a SIGTERM signal
file=/var/run/myscript.pid
echo $$ > "$file"

while true
do
	echo "To infinity and beyond"
	sleep 2

	trap 'echo "Y U no love me?!"' SIGINT
	trap 'rm $file; exit' SIGQUIT
	trap 'echo I hate the kill command; rm $file; exit' SIGTERM
done
