#!/usr/bin/env bash
# Bash script that displays numbers from 1 to 100

FILE="school"

if [ -e "$FILE" ]; 
then
    echo "school file exists"
    if [ -s "$FILE" ]; 
    then
        echo "school file is not empty"
    else
        echo "school file is empty"
    if [ -f "$FILE" ]; 
    then
        echo "school is a regular file"
    else
    echo "school file does not exist"
    fi
done
