#!/usr/bin/env bash
# Bash script that displays the visitor IP along with
# the HTTP status code from the Apache log file
awk '{print $1, $9}' /var/log/apache2/access.log | sort | uniq -c | awk '{print $2, $3, $1}'
