#!/usr/bin/env bash
# Bash script that displays Best School 10 times.

a=1
while [ $a -le 10 ]
do
    if [ $a -eq 9 ]
    then
        echo "Best School"
        echo "Hi"
    else
        echo "Best School"
    fi
    a=$((a+1))
done
