#!/usr/bin/env bash
# use case statement.

x=1
while [ $x -le 20 ]
do
    case $x in
        4)
            echo "$x bad luck from China"
            ;;
        9)
            echo "$x bad luck from Japan"
            ;;
        17)
            echo "$x bad luck from Italy"
            ;;
        *)
            echo $x
            ;;
    esac
    x=$((x+1))
done
